.TH cdcat 1
.SH NAME
cdcat \- media catalog program
.SH SYNOPSIS
.B cdcat
.SH "DESCRIPTION"
This manual page documents briefly the
.BR cdcat ,
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
.B cdcat 
is a graphical, multiplatform media catalog program which scans the
directories/media you specify and makes a list of the filesystem (including
the tags of MP3s) and stores the result in a gzipped XML file.
.SH AUTHOR
This manual page was written by Jorge Bernal <koke@sindominio.net>,
for the Debian GNU/Linux system (but may be used by others).
