// Add C includes here

#if defined __cplusplus
// Add C++ includes here
#include <iostream>
#include <QGroupBox>
#include <QFrame>
#include <QGridLayout>
#include <QGroupBox>
#include <QHBoxLayout>
#include <QListView>
#include <QTextEdit>
#include <QList>
#include <QTableView>
#include <QTextBrowser>
#include <QList>
#include <QVBoxLayout>
#include <QApplication>
#include <QCalendarWidget>
#include <QCheckBox>
#include <qcheckbox.h>
#include <QCloseEvent>
#include <qcolor.h>
#include <qcombobox.h>
#include <QDate>
#include <QDateTime>
#include <QDateTimeEdit>
#include <qdatetime.h>
#include <QDialog>
#include <QDir>
#include <QDragEnterEvent>
#include <QDragLeaveEvent>
#include <QDragMoveEvent>
#include <QDropEvent>
#include <QEvent>
#include <qevent.h>
#include <QFileDialog>
#include <qfiledialog.h>
#include <QFile>
#include <QFile>
#include <QFileInfo>
#include <QFileInfo>
#include <QFont>
#include <QFontMetrics>
#include <QImage>
#include <QKeyEvent>
#include <QLabel>
#include <QLabel>
#include <QLatin1String>
#include <QLayout>
#include <QLayout>
#include <QLayout>
#include <qlineedit.h>
#include <QList>
#include <qlist.h>
#include <QLocale>
#include <QMenuBar>
#include <QMessageBox>
#include <qmessagebox.h>
// #include <qmime.h>
#include <QMouseEvent>
#include <qobject.h>
#include <qpainter.h>
#include <QPaintEvent>
#include <qpalette.h>
#include <QPixmap>
#include <QPixmap>
// #include <QPlastiqueStyle>
#include <qpoint.h>
#include <QProgressDialog>
#include <qprogressdialog.h>
#include <qpushbutton.h>
#include <qradiobutton.h>
#include <QRegExp>
#include <qregexp.h>
#include <QResizeEvent>
#include <QSpinBox>
#include <qspinbox.h>
#include <QSplitter>
#include <QString>
#include <qstring.h>
#include <QStringList>
#include <qstringlist.h>
#include <QFrame>
#include <QTextEdit>
#include <qtabwidget.h>
#include <QtCore/QVariant>
#include <QtDebug>
#include <QTextBrowser>
#include <qtextbrowser.h>
#include <qtextcodec.h>
#include <QTextStream>
#include <qtextstream.h>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDateTimeEdit>
#include <QtWidgets/QDialog>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QVBoxLayout>
#include <qtimer.h>
#include <QToolButton>
#include <QToolTip>
#include <qtranslator.h>
#include <QtXml/QXmlAttributes>
#include <QtXml/QXmlDefaultHandler>
#include <QtXml/QXmlInputSource>
#include <QtXml/QXmlLocator>
#include <QVariant>
#include <qwidget.h>
#endif
