// Add C includes here

#if defined __cplusplus
// Add C++ includes here
#include <iostream>
#include <QGroupBox>
#include <QFrame>
#include <QGridLayout>
#include <QGroupBox>
#include <QHBoxLayout>
#include <QListView>
#include <QTextEdit>
#include <QList>
#include <QTableView>
#include <QTextBrowser>
#include <QList>
#include <QVBoxLayout>
#include <QApplication>
#include <QCalendarWidget>
#include <QCheckBox>
#include <QCheckBox>
#include <QCloseEvent>
#include <QColor>
#include <QComboBox>
#include <QDate>
#include <QDateTime>
#include <QDateTimeEdit>
#include <QDateTime>
#include <QDialog>
#include <QDir>
#include <QDragEnterEvent>
#include <QDragLeaveEvent>
#include <QDragMoveEvent>
#include <QDropEvent>
#include <QEvent>
#include <QEvent>
#include <QFileDialog>
#include <QFileDialog>
#include <QFile>
#include <QFile>
#include <QFileInfo>
#include <QFileInfo>
#include <QFont>
#include <QFontMetrics>
#include <QImage>
#include <QKeyEvent>
#include <QLabel>
#include <QLabel>
#include <QLatin1String>
#include <QLayout>
#include <QLayout>
#include <QLayout>
#include <QLineEdit>
#include <QList>
#include <QList>
#include <QLocale>
#include <QMenuBar>
#include <QMessageBox>
#include <QMessageBox>
#include <QMouseEvent>
#include <QObject>
#include <QPainter>
#include <QPaintEvent>
#include <QPalette>
#include <QPixmap>
#include <QPixmap>
// #include <QPlastiqueStyle>
#include <QPoint>
#include <QProgressDialog>
#include <QProgressDialog>
#include <QPushButton>
#include <QRadioButton>
#include <QRegExp>
#include <QRegExp>
#include <QResizeEvent>
#include <QSpinBox>
#include <QSpinBox>
#include <QSplitter>
#include <QString>
#include <QString>
#include <QStringList>
#include <QStringList>
#include <QFrame>
#include <QTextEdit>
#include <QTabWidget>
#include <QtCore/QVariant>
#include <QtDebug>
#include <QTextBrowser>
#include <QTextBrowser>
#include <QTextCodec>
#include <QTextStream>
#include <QTextStream>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDateTimeEdit>
#include <QtWidgets/QDialog>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QVBoxLayout>
#include <QTimer>
#include <QToolButton>
#include <QToolTip>
#include <QTranslator>
#include <QtXml/QXmlAttributes>
#include <QtXml/QXmlDefaultHandler>
#include <QtXml/QXmlInputSource>
#include <QtXml/QXmlLocator>
#include <QVariant>
#include <QWidget>
#endif
